add controllers, technical assignment - 13
S-Gilliver/java-shareit pull request #1
Opened 2023-10-30 13:16 UTC by S-Gilliver

2023-10-30 18:18 UTC, kalitva requested changes

2023-10-30 18:18 UTC, kalitva commented on pom.xml
> +			<artifactId>logback-classic</artifactId>
А разве логбэк надо отдельно подключать? Насколько я знаю, сприг-бут использует по дефолту именно логбэк (но могу ошибаться)

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + */
Поудаляй эти комменты

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Давай вместо даты лучше использовать 

```java
@Getter
@Setter
```

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +//измена
Чего?) Удали этот коммент

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDtoById(Item item) {
Лучше
`toItemDtoById --> toDto`

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private Item validateItemById(ItemDto itemDto, int userId) {
1. `validateItemById --> validateItem`
2. Метод должен быть `void`

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Item oldItem = itemStorage.getItemById(itemDto.getId());
Это не является валидацией, принимай то, что нужно проверить в параметрах метода

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            oldItem.setName(itemDto.getName());
Это тоже не является валидацией, вынеси из метода

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ValidationException("Item has not been validated");
Вот это валидация (и также блок на 99 линии)

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +     return User.builder()
Пустая линия между объявлениями полей и методов

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +import static ru.practicum.shareit.user.mapper.UserMapper.mapToUser;
Давай не будем использовать статические импорты (исключение - классы юнит тестов)

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (User user : users) {
Создай в сторадже метод `boolean existsByEmail(String email)`, который возвращает `boolean`. Здесь будешь вызывать этто метод бросать\не бросать исключение в зависимости от результата вызова

2023-10-30 18:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    }
Все тоже самое, что я писал для подобного метода выше

2023-10-31 18:26 UTC, kalitva requested changes

2023-10-31 18:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                              @RequestHeader("X-Sharer-User-Id") int userId) {
Давай `X-Sharer-User-Id` вынесем в коснтанту

2023-10-31 18:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        .getItemRequest((int) itemDto.getRequest().getId()) : null)
Давай лучше это выражение вынесем в переменную (выделить и затем `ctrl + alt + v`)

2023-10-31 18:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemStorage.getItems()
Вот это лучше вычислять в сторадже, создай метод `findItemsByUserId` и перенеси туда эти вычисления

2023-10-31 18:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (Item item : itemsList) {
Не используй в названиях коллекций (и методов соответственно) слова типа `List Map Set Array` и.т.п
`itemList --> items`

2023-10-31 18:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +     return User.builder()
?

2023-10-31 18:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void validateUser(User oldUser) {
Три метода с одинаковым название, тое есть они одно и то же делают? Если нет, отобрази это в названиях

2023-10-31 18:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    public boolean existsByEmail(String email, int userId) {
Не понял зачем второй такой же? (объяснять в комментах не надо, просто поправь код так, чтобы не было вопросов)

2023-10-31 19:33 UTC, S-Gilliver commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    public boolean existsByEmail(String email, int userId) {
Он нужен, из-за того что если у нас обновляется почта, то он выбрасывает ошибку, поэтому пришлось сделать еще один метод, который не проверяет user, которого мы обновляем, передавая методу user id.

2023-11-01 18:34 UTC, kalitva approved these changes

2023-11-01 18:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    String description;
private

2023-11-01 18:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String USER_HEADER = "X-Sharer-User-Id";
Лучше `USER_ID_HEADER`

2023-11-01 18:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +@Data
Нет необходимости делать сеттеры\геттеры в сервисах, удали `@Data`

2023-11-01 18:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validateItemData(Item oldItem) {
`validateItemData --> validateItem`

2023-11-02 01:35 UTC, merged