add booking, technical assignment - 14
S-Gilliver/java-shareit pull request #2
Opened 2023-11-02 21:18 UTC by S-Gilliver

2023-11-03 19:29 UTC, kalitva requested changes

2023-11-03 19:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Вместо определения всех этих методов для фильтрации объектов можно воспользоваться `Specification`, попробуй, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-11-03 19:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void validateBookingData(Booking booking) {
Мы же уже обсуждали проблему невнятного нэйминга ...

https://github.com/S-Gilliver/java-shareit/pull/1#discussion_r1379165196
https://github.com/S-Gilliver/java-shareit/pull/1#discussion_r1378010741

2023-11-03 19:34 UTC, S-Gilliver commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void validateBookingData(Booking booking) {
Это я помню, просто у меня два валидатора и называть одинаковыми именами я думаю не стоит

2023-11-05 11:24 UTC, kalitva approved these changes

2023-11-05 11:24 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +    public static List<CommentDto> mapToCommentsDto(List<Comment> comments) {
`mapToCommentsDto --> mapToCommentDtos`

2023-11-05 11:24 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDtoBooking mapToItemDtoBooking(Optional<Booking> bookingPast, Optional<Booking> bookingFuture, Item item) {
Не используй `Optional`  как параметры методов

2023-11-05 11:24 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> -    private User requester;
Почкму передалал? Здесь должен быть `User`

2023-11-05 11:24 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new BadRequestException("User data not validated: " + new ArrayList<>(violations).get(0).getMessage());
Почему передаешь только первый элемент?

2023-11-05 12:11 UTC, S-Gilliver commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> -    private User requester;
Случайно сделал, исправил

2023-11-05 12:11 UTC, S-Gilliver commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new BadRequestException("User data not validated: " + new ArrayList<>(violations).get(0).getMessage());
Тоже поправил

2023-11-05 12:23 UTC, merged